# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-zm3p0.eu-north-1.aws.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username={{SASL_USERNAME}}
sasl.password={{SASL_PASSWORD}}

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000
client.id=ccloud-python-client-b4e21528-85e5-4f41-a566-a90c6ee0cb9c

# R�ponse imm�diate du broker pour �viter de bloquer l?envoi
acks=all
# R�essayer moins souvent pour �viter des d�lais inutiles
retries=3
# Ne pas attendre avant d?envoyer un message (par d�faut, il attend un peu)
linger.ms=1
# Doubler la taille du batch pour �viter d?attendre plus de messages
batch.size=32768
# Si Kafka ne r�pond pas en 5 sec, r�essayer
request.timeout.ms=5000
#  V�rifier plus souvent les brokers Kafka
metadata.max.age.ms=5000
