# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-zm3p0.eu-north-1.aws.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=IRDWJO5LZ7VTO2BG
sasl.password=ymYfbxLcsFU26yspgnibXdiqta3jiiCp1H1PA4IrurKw07s7Zty6GG7bAj9Sfagc

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-python-client-5e965551-cec4-4e86-9248-d4a524591624
