# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-zm3p0.eu-north-1.aws.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username={{SASL_USERNAME}}
sasl.password={{SASL_PASSWORD}}

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000
client.id=ccloud-python-client-b4e21528-85e5-4f41-a566-a90c6ee0cb9c

# Réponse immédiate du broker pour éviter de bloquer l?envoi
acks=all
# Réessayer moins souvent pour éviter des délais inutiles
retries=3
# Ne pas attendre avant d?envoyer un message (par défaut, il attend un peu)
linger.ms=1
# Doubler la taille du batch pour éviter d?attendre plus de messages
batch.size=32768
# Si Kafka ne répond pas en 5 sec, réessayer
request.timeout.ms=5000
#  Vérifier plus souvent les brokers Kafka
metadata.max.age.ms=5000
